name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        # Install dependencies using the same Python version FontForge embeds
        - python-version: "3.10"
          fontforge-url: https://github.com/fontforge/fontforge/releases/download/20230101/FontForge-2023-01-01-a1dad3e-x86_64.AppImage
          allowlists:
          - ignore.txt
          - deprecated.txt
          - 20251009.txt
        - python-version: "3.10"
          fontforge-url: https://github.com/fontforge/fontforge/releases/download/20251009/FontForge-2025-10-09-Linux-x86_64.AppImage
          allowlists:
          - ignore.txt
          - deprecated.txt

    steps:
    - uses: actions/checkout@v5
    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.21"
        python-version: ${{ matrix.config.python-version }}
        enable-cache: true
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Fetch FontForge
      run: |
        wget -O FontForge.AppImage ${{ matrix.config.fontforge-url }}
        chmod u+x FontForge.AppImage
        ./FontForge.AppImage --appimage-extract
    - name: Run stubtest
      run: |
        ./squashfs-root/AppRun -script "${GITHUB_WORKSPACE}/tests/run_stubtest.py" "${GITHUB_WORKSPACE}/.venv/lib/python${{ matrix.config.python-version }}/site-packages" ${{ join(matrix.config.allowlists, ' ') }}
